config/routes.rb
Rails.application.routes.draw do
  resources :my_dairies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_dairy.rb
class MyDairy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/my_dairies_controller.rb
class MyDairiesController < ApplicationController
  before_action :set_my_dairy, only: [:show, :edit, :update, :destroy]

  # GET /my_dairies
  # GET /my_dairies.json
  def index
    @my_dairies = MyDairy.all
  end

  # GET /my_dairies/1
  # GET /my_dairies/1.json
  def show
  end

  # GET /my_dairies/new
  def new
    @my_dairy = MyDairy.new
  end

  # GET /my_dairies/1/edit
  def edit
  end

  # POST /my_dairies
  # POST /my_dairies.json
  def create
    content = "朝食は" + params[:my_dairy][:question1] + "\n" + "昼食は" + params[:my_dairy][:question2] + "\n" + "夕食は" + params[:my_dairy][:question3]
    @my_dairy = MyDairy.new(content: content)

    respond_to do |format|
      if @my_dairy.save
        format.html { redirect_to @my_dairy, notice: 'My dairy was successfully created.' }
        format.json { render :show, status: :created, location: @my_dairy }
      else
        format.html { render :new }
        format.json { render json: @my_dairy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_dairies/1
  # PATCH/PUT /my_dairies/1.json
  def update
    respond_to do |format|
      if @my_dairy.update(my_dairy_params)
        format.html { redirect_to @my_dairy, notice: 'My dairy was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_dairy }
      else
        format.html { render :edit }
        format.json { render json: @my_dairy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_dairies/1
  # DELETE /my_dairies/1.json
  def destroy
    @my_dairy.destroy
    respond_to do |format|
      format.html { redirect_to my_dairies_url, notice: 'My dairy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_dairy
      @my_dairy = MyDairy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def my_dairy_params
      params.require(:my_dairy).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_dairies_helper.rb
module MyDairiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dairy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/my_dairies/_form.html.erb
<%= form_with(model: my_dairy, local: true) do |form| %>
  <% if my_dairy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_dairy.errors.count, "error") %> prohibited this my_dairy from being saved:</h2>

      <ul>
        <% my_dairy.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label "朝食はなんですか？" %>
  <%= form.text_area :question1 %>
</div>

<div class="field">
<%= form.label "昼食はなんですか？" %>
<%= form.text_area :question2 %>
</div>

  <div class="field">
    <%= form.label "夕食はなんですか？" %>
    <%= form.text_area :question3 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/my_dairies/edit.html.erb
<h1>Editing My Dairy</h1>

<%= render 'form', my_dairy: @my_dairy %>

<%= link_to 'Show', @my_dairy %> |
<%= link_to 'Back', my_dairies_path %>

app/views/my_dairies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Dairies</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_dairies.each do |my_dairy| %>
      <tr>
        <td><%= my_dairy.content %></td>
        <td><%= link_to 'Show', my_dairy %></td>
        <td><%= link_to 'Edit', edit_my_dairy_path(my_dairy) %></td>
        <td><%= link_to 'Destroy', my_dairy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Dairy', new_my_dairy_path %>

app/views/my_dairies/new.html.erb
<h1>New My Dairy</h1>

<%= render 'form', my_dairy: @my_dairy %>

<%= link_to 'Back', my_dairies_path %>

app/views/my_dairies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @my_dairy.content %>
</p>

<%= link_to 'Edit', edit_my_dairy_path(@my_dairy) %> |
<%= link_to 'Back', my_dairies_path %>